---
title: "Overview"
author: "Tobi & Lukas"
date: "Rendered `r format(Sys.time(), '%F %H:%M')`"
output:
  html_document
---

```{r overview, include=FALSE}
source("setup.R")

theme_set(theme_ipsum(base_size = 14))
```

Seit dem Wintersemester 15/16 führen wir TutorInnen ein Spreadsheet mit der Teilnehmerzahl pro Tutorium. Es werden keine individuellen Personen vermerkt — das wäre ja albern — wir führen lediglich Buch darüber, wie viele Leute an einem Termin aufgetaucht sind.  

## Raw data overview

```{r firstlook}
participation %>%
  datatable(style = "bootstrap", rownames = F, 
            fillContainer = T, 
            height = 100,
            options = list(
              bInfo = F,
              paging = F,
              autoWidth = TRUE,
              sDom  = '<"top">lrt<"bottom">ip'), 
            caption = "QM Participation")
```

```{r all_semesters_raw_perdate}
ggplot(data = participation, aes(x = Datum, y = Teilnehmerzahl)) +
  geom_col(position = "dodge") +
  facet_wrap(~Studienjahr, ncol = 1, scales = "free_x", labeller = label_both) +
  scale_x_date(date_breaks = "1 month",
               date_labels = "%b %y") +
  labs(title = "Tutorienteilnehmerschaft",
       subtitle = "Insgesamt",
       x = "", y = "Teilnehmerzahl")
```

## TutorInnen

```{r all_semesters_per_tutorIn}
ggplot(data = participation, 
       aes(x = forcats::fct_reorder(TutorIn, Teilnehmerzahl, fun = mean), 
           y = Teilnehmerzahl,
           color = TutorIn)) +
  geom_boxplot(alpha = .75) +
  stat_summary(fun.y = mean, geom = "point", size = 2.5, color = "black") +
  stat_summary(fun.y = mean, geom = "point", size = 1.5) +
  geom_hline(yintercept = mean(participation$Teilnehmerzahl, na.rm = T),
             linetype = "dashed") +
  scale_color_brewer(palette = "Paired", guide = F) +
  coord_flip() +
  labs(title = "Durchnittliche Teilnehmerzahl pro TutorIn",
       subtitle = "Boxplot + Mittelwert",
       x = "TutorIn", y = "Teilnehmerzahl",
       caption = "Daten aus allen Semestern")
```


## Participation overview

### Distributions

```{r all_semesters_freq}
ggplot(data = participation, aes(x = Teilnehmerzahl)) +
  geom_histogram(binwidth = 1, alpha = .75) +
  labs(title = "Teilnahmen pro Tutorium",
       subtitle = "Alle Semester",
       x = "TeilnehmerInnen", y = "Häufigkeit")


ggplot(data = participation, aes(x = Teilnehmerzahl)) +
  geom_histogram(binwidth = 1, alpha = .75) +
  facet_grid(Studienjahr ~ Semester) +
  labs(title = "Teilnahmen pro Tutorium",
       subtitle = "Alle Semester",
       x = "TeilnehmerInnen", y = "Häufigkeit")
```

### Sums

```{r all_semesters_sum, fig.height=8}
participation %>%
  group_by(Semester, Studienjahr, Aufgabenblatt) %>%
  summarize(Teilnehmerzahl = sum(Teilnehmerzahl)) %>%
  ungroup() %>%
  ggplot(aes(x = Aufgabenblatt, y = Teilnehmerzahl,
             color = Studienjahr, fill = Studienjahr)) +
  geom_line() +
  geom_point(size = 3, shape = 21, stroke = 1.5, color = "white") +
  facet_grid(Studienjahr ~ Semester, labeller = label_both) +
  scale_x_continuous(breaks = seq(0, 100, 3), minor_breaks = seq(0, 100, 1)) +
  scale_color_brewer(palette = "Set1", guide = F) +
  scale_fill_brewer(palette = "Set1", guide = F) +
  labs(title = "QM Tutorienteilnehmerschaft",
       subtitle = "Gesamtteilnahme pro Woche",
       y = "Summe der Teilnehmerzahlen")
```

### Means

```{r all_semesters_mean}
participation %>%
  ggplot(aes(x = Aufgabenblatt, y = Teilnehmerzahl,
             color = Studienjahr, fill = Studienjahr)) +
  stat_summary(fun.data = mean_cl_normal, geom = "ribbon", 
               size = .5, alpha = .6) +
  stat_summary(fun.y = mean, geom = "path", size = 1.5, color = "black") +
  stat_summary(fun.y = mean, geom = "path", size = .5) +
  facet_grid(Studienjahr ~ Semester, labeller = label_both) +
  scale_x_continuous(breaks = seq(0, 100, 3), minor_breaks = seq(0, 100, 1)) +
  scale_color_brewer(palette = "Set1", guide = F) +
  scale_fill_brewer(palette = "Set1", guide = F) +
  labs(title = "QM Tutorienteilnehmerschaft",
       subtitle = "Durchschnittliche Teilnahme pro Woche + 95% CI",
       y = "Mittlere Teilnehmerzahl + 95% CI")
```

## Weekdays

```{r all_semester_weekdays}
participation %>%
  ggplot(aes(x = forcats::fct_rev(Tag), y = Teilnehmerzahl)) +
  stat_summary(fun.data = mean_cl_normal, geom = "errorbar", size = 1) +
  stat_summary(fun.y = mean, geom = "point", size = 2, color = "white", shape = 21, stroke = 1.5) +
  stat_summary(fun.y = mean, geom = "point", size = 1.5) + # this doesn't do anything, does it?
  geom_hline(yintercept = mean(participation$Teilnehmerzahl, na.rm = T),
             linetype = "dashed") +
  coord_flip() +
  scale_color_brewer(palette = "Set1", guide = F) +
  labs(title = "QM Tutorienteilnehmerschaft",
       subtitle = "Durchschnittliche Teilnahme pro Wochentag + 95% CI",
       x = "Tag",
       y = "Mittlere Teilnehmerzahl + 95% CI")

participation %>%
  ggplot(aes(x = forcats::fct_rev(Tag), y = Teilnehmerzahl,
             color = Studienjahr, fill = Studienjahr)) +
  stat_summary(fun.data = mean_cl_normal, geom = "errorbar", size = .75) +
  stat_summary(fun.y = mean, geom = "point", shape = 21, size = 1.75, stroke = 1, color = "white") +
  coord_flip() +
  facet_grid(Studienjahr ~ Semester, labeller = label_both) +
  scale_color_brewer(palette = "Set1", guide = F) +
  scale_fill_brewer(palette = "Set1", guide = F) +
  labs(title = "QM Tutorienteilnehmerschaft",
       subtitle = "Durchschnittliche Teilnahme pro Wochentag + 95% CI",
       x = "Tag",
       y = "Mittlere Teilnehmerzahl + 95% CI")
```

### ANOVA

```{r all_semesters_weekday_anova}
model <- aov(Teilnehmerzahl ~ Tag, data = participation)

tadaa_aov(Teilnehmerzahl ~ Tag, data = participation, print = "markdown")

TukeyHSD(model) %>%
  tidy() %>%
  mutate(signif = if_else(adj.p.value < 0.05, "Signifikant", "Nicht Signifikant"),
         comparison = stringr::str_replace(comparison, "-", " - ")) %>%
  ggplot(data = ., aes(x = reorder(comparison, estimate), 
                       y = estimate, 
                       ymin = conf.low, ymax = conf.high,
                       color = signif, fill = signif)) +
  geom_errorbar(width = .5, size = .75) +
  geom_point(shape = 21, size = 1.5, stroke = 1, color = "white") +
  geom_hline(yintercept = 0, linetype = "dashed", color = "black") +
  coord_flip() +
  scale_color_brewer(palette = "Set1", direction = -1) +
  scale_fill_brewer(palette = "Set1", direction = -1, guide = F) +
  labs(title = "Tukey HSD Post Hoc Test",
       subtitle = "Estimates mit 95% CI",
       x = "Vergleich", y = "Estimate + 95% CI", color = "") +
  theme(legend.position = "top")
```

